Milestone4
hemant-soni-vst-au4/calculator pull request #4
Opened 2021-01-02 18:30 UTC by hemant-soni-vst-au4

- logic folder created
- operate module to calculate total
- calculate module to pass the calculator data object and button name

2021-01-02 18:46 UTC, rOluochKe requested changes
Hello @hemant-soni-vst-au4 
### You have done well so far :clap: However, you have an issue to fix:-
- [ ] Make the demo link display the calculator, currently, it displays an error.
### Fix the issue and submit for another code review. Good luck.
- Happy coding!

2021-01-03 14:25 UTC, hemant-soni-vst-au4 commented
- live link is working now.
-  Styling of the calculator will be done in milestone 5

2021-01-03 15:12 UTC, sumancrest0001 commented
**Status: Approved :clap: :100: 
Congratulations @hemant-soni-vst-au4,**
Thank you for implementing the change requested by the previous TSE. Now, the live link is working correctly.

Happy coding !!!

Before moving to the next milestone, please consider the following points.

2021-01-03 15:17 UTC, sumancrest0001 approved these changes
[Optional] You have assigned the same key for all the buttons in the ButtonPanel file which resulted in an error. We can fix that.

2021-01-03 15:17 UTC, sumancrest0001 commented on src/logic/calculate.js
> +      break;
[Optional] It would have been nice if you added logic for the operations as well.

2021-01-03 15:41 UTC, merged